[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.2.0"
license = "MIT"

[workspace.dependencies]
noleader = { path = "crates/noleader" }

anyhow = { version = "1.0.71" }
tokio = { version = "1", features = ["full"] }
tracing = { version = "0.1", features = ["log"] }
