[package]
name = "noleader"
edition = "2024"
readme = "../../README.md"
version.workspace = true
license.workspace = true
repository = "https://git.front.kjuulh.io/kjuulh/noleader"
authors = ["kjuulh <contact@kasperhermansen.com>"]
description = "A small leader election package using NATS keyvalue store as the distributed locking mechanism. Does not require a min / max set of nodes"

[dependencies]
anyhow.workspace = true
tracing.workspace = true

async-nats = "0.42"
uuid = { version = "1", features = ["v4", "v7"] }
bytes = "1"
tokio.workspace = true
tokio-util = "0.7"
rand = "0.9.1"
async-trait = "0.1.89"
# fork until dangerous set migrate table name is stable. Should be any version after 8.6
sqlx = { git = "https://github.com/launchbadge/sqlx", features = [
  "uuid",
  "postgres",
  "runtime-tokio",
  "tls-rustls",
], rev = "064d649abdfd1742e5fdcc20176a6b415b9c25d3" }

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
